# Gopher map generator
# This is a utility to convert text files and csv index generated by jsonToText.py to gopher maps.
# Check my gopher homepage here: gopher://sdf.org:70/users/pengan/

import csv
import shutil
from tkinter import Y
dataDict = {}
with open('index.csv', newline='') as csvfile:
    idxreader = csv.reader(csvfile, delimiter=',')
    for row in idxreader:
        articleid = int(row[0])
        dataDict[articleid] = row
print(str(dataDict.__len__())+" articles read")
sortedKeys = sorted(dataDict.keys())

gopherByYear = {}
for key in sortedKeys:
    article = dataDict[key]
    articleidStr = article[0]
    title = article[1]
    date = article[2]
    year = date[0:4]
    dateNoTime = date[0:10]
    filename = articleidStr+'.txt'
    newFileName = year+'\\'+filename
    shutil.copy(filename, newFileName)
    gopherMapEntry = '0('+dateNoTime+') '+title+'\t'+filename+'\n'


    print(newFileName)
    if not year in gopherByYear:
        gopherByYear[year] = []
    gopherByYear[year].append(gopherMapEntry)
for year in gopherByYear.keys():
    lines = gopherByYear[year]
    gophermapPath = year+'\\gophermap'
    headline = '1Homepage\t/users/pengan\n\n'
    with open(gophermapPath,mode='w') as gophermap:
        gophermap.write(headline)
        gophermap.writelines(lines)